# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='%Y-%m-%d')),
                ('debito', models.CharField(max_length=20)),
                ('credito', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('historico', models.CharField(max_length=200)),
                ('conta_devedora', models.CharField(max_length=50)),
                ('conta_credora', models.CharField(max_length=50)),
            ],
        ),
    ]
