# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='historico',
            new_name='history',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='conta_credora',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='conta_devedora',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='debito',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='valor',
        ),
        migrations.AddField(
            model_name='accounting',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounting',
            name='credit',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounting',
            name='debit',
            field=models.CharField(default='next', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounting',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
