# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180121_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='conta_credora',
            field=models.CharField(default='to be provided', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounting',
            name='conta_devedora',
            field=models.CharField(default='to be provided', max_length=20),
            preserve_default=False,
        ),
    ]
