# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180121_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='comnpany',
            field=models.CharField(default='neXThinking', max_length=200),
            preserve_default=False,
        ),
    ]
