# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accounting_comnpany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='comnpany',
        ),
    ]
