# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_accounting_comnpany'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='company',
            field=models.CharField(default='Nexthinking', max_length=20),
            preserve_default=False,
        ),
    ]
