# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_accounting_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='conta_credora',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='conta_devedora',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='credit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='debit',
            field=models.CharField(max_length=100),
        ),
    ]
