# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20180121_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
