# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-26 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='n',
        ),
        migrations.AlterField(
            model_name='input',
            name='r',
            field=models.DateTimeField(),
        ),
    ]
