# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-26 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20180126_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
    ]
